import "./globals.css";
import { ReactNode } from "react";
import type { Metadata } from "next";
import { Outfit } from "next/font/google";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SolCraft",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: ReactNode }>) {
  return (
    <html lang="en">
      <body className={outfit.className}>
        {children}
      </body>
    </html>
  );
}
